steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/tdf-docker/tdf-web:latest', '--build-arg', 'NEXT_PUBLIC_RAZORPAY_KEY_ID=rzp_live_SvajhCMpUgsAkZ', '.']
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/tdf-docker/tdf-web:latest'
